[versions]
agp = "8.5.0"
appCenter = "5.0.4"
kotlin = "2.0.0"
ksp = "2.0.0-1.0.22"
lifecycle = "2.8.2"
materialDialog = "3.3.0"
sealedEnum = "0.7.0"

[libraries]
appcenter-analytics = { module = "com.microsoft.appcenter:appcenter-analytics", version.ref = "appCenter" }
appcenter-crashes = { module = "com.microsoft.appcenter:appcenter-crashes", version.ref = "appCenter" }
android-tools = { module = "com.android.tools.build:gradle", version.ref = "agp" }
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.8.0" }
androidx-browser = { module = "androidx.browser:browser", version = "1.8.0" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.3.2" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.13.1" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.0" }
eclipse-jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version = "6.10.0.202406032230-r" }
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version = "4.3" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version = "1.17.0" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.8.1" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.7.0" }
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-common = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
material = { module = "com.google.android.material:material", version = "1.12.0" }
material-dialogs-core = { module = "com.afollestad.material-dialogs:core", version.ref = "materialDialog" }
material-dialogs-input = { module = "com.afollestad.material-dialogs:input", version.ref = "materialDialog" }
xposed = { module = "de.robv.android.xposed:api", version = "82" }
flexbox = { module = "com.google.android.flexbox:flexbox", version = "3.0.0" }
colorpicker = { module = "com.jaredrummler:colorpicker", version = "1.1.0" }
ezXHelper = { module = "com.github.kyuubiran:EzXHelper", version = "1.0.3" }
confetti = { module = "com.github.jinatonic.confetti:confetti", version = "1.1.2" }
weatherView = { module = "com.github.MatteoBattilana:WeatherView", version = "3.0.0" }
sealedEnum-runtime = { module = "com.github.livefront.sealed-enum:runtime", version.ref = "sealedEnum" }
sealedEnum-ksp = { module = "com.github.livefront.sealed-enum:ksp", version.ref = "sealedEnum" }
glide = { module = "com.github.bumptech.glide:glide", version = "4.16.0" }
byte-buddy = { module = "net.bytebuddy:byte-buddy", version = "1.14.17" }
dalvik-dx = { module = "com.jakewharton.android.repackaged:dalvik-dx", version = "14.0.0_r21" }
flatbuffers-java = { module = "com.google.flatbuffers:flatbuffers-java", version = "23.5.26" }
davemorrissey-subsampling-scale-image-view = { module = "com.davemorrissey.labs:subsampling-scale-image-view-androidx", version = "3.10.0" }
google-protobuf = { module = "com.google.protobuf:protobuf-java", version = "4.27.1" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version = "2.2.0" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version = "11.2.1" }
