blank_issues_enabled: false
contact_links:
  - name: Group
    url: https://t.me/QAuxiliaryChat
    about: Our Telegram Group 
  - name: smart-question
    url: http://www.catb.org/~esr/faqs/smart-questions.html
    about: READ BEFORE YOU ASKING ANY QUESTION
